### ISSUE TITLE
Install command fails on macOS

### ISSUE THREAD

**Issue by hernanmd** [gcla/gowid#3] opened 2019-04-28 22:28 UTC
On macOS High Sierra 10.13.6 the install command fails:

```
$ env | grep GOPATH
GOPATH=/Users/hernan/go

$ go get github.com/gcla/gowid/...
```

Output:

```
go get github.com/gcla/gowid/examples/gowid-asciigraph: open /bin/gowid-asciigraph: permission denied
go get github.com/gcla/gowid/examples/gowid-fib: open /bin/gowid-fib: permission denied
go get github.com/gcla/gowid/examples/gowid-editor: open /bin/gowid-editor: permission denied
go get github.com/gcla/gowid/examples/gowid-dir: open /bin/gowid-dir: permission denied
go get github.com/gcla/gowid/examples/gowid-graph: open /bin/gowid-graph: permission denied
go get github.com/gcla/gowid/examples/gowid-helloworld: open /bin/gowid-helloworld: permission denied
go get github.com/gcla/gowid/examples/gowid-overlay1: open /bin/gowid-overlay1: permission denied
go get github.com/gcla/gowid/examples/gowid-menu: open /bin/gowid-menu: permission denied
go get github.com/gcla/gowid/examples/gowid-overlay3: open /bin/gowid-overlay3: permission denied
go get github.com/gcla/gowid/examples/gowid-overlay2: open /bin/gowid-overlay2: permission denied
go get github.com/gcla/gowid/examples/gowid-palette: open /bin/gowid-palette: permission denied
go get github.com/gcla/gowid/examples/gowid-tree: open /bin/gowid-tree: permission denied
go get github.com/gcla/gowid/examples/gowid-terminal: open /bin/gowid-terminal: permission denied
go get github.com/gcla/gowid/examples/gowid-tutorial1: open /bin/gowid-tutorial1: permission denied
go get github.com/gcla/gowid/examples/gowid-tutorial2: open /bin/gowid-tutorial2: permission denied
go get github.com/gcla/gowid/examples/gowid-tutorial3: open /bin/gowid-tutorial3: permission denied
go get github.com/gcla/gowid/examples/gowid-tutorial4: open /bin/gowid-tutorial4: permission denied
go get github.com/gcla/gowid/examples/gowid-table: open /bin/gowid-table: permission denied
go get github.com/gcla/gowid/examples/gowid-tutorial5: open /bin/gowid-tutorial5: permission denied
go get github.com/gcla/gowid/examples/gowid-widgets1: open /bin/gowid-widgets1: permission denied
go get github.com/gcla/gowid/examples/gowid-tutorial6: open /bin/gowid-tutorial6: permission denied
go get github.com/gcla/gowid/examples/gowid-widgets2: open /bin/gowid-widgets2: permission denied
go get github.com/gcla/gowid/examples/gowid-widgets3: open /bin/gowid-widgets3: permission denied
go get github.com/gcla/gowid/examples/gowid-widgets5: open /bin/gowid-widgets5: permission denied
go get github.com/gcla/gowid/examples/gowid-widgets4: open /bin/gowid-widgets4: permission denied
go get github.com/gcla/gowid/examples/gowid-widgets6: open /bin/gowid-widgets6: permission denied
go get github.com/gcla/gowid/examples/gowid-widgets7: open /bin/gowid-widgets7: permission denied
go get github.com/gcla/gowid/examples/gowid-widgets8: open /bin/gowid-widgets8: permission denied
```

Should I run the command as root?

**Comment by gcla** [comment] 2019-04-28 23:53
hi @hernanmd - no, sudo/root shouldn't be necessary. Would you mind sending me the output of 

$ go env

and 

$ go version

**Comment by hernanmd** [comment] 2019-04-29 00:09
Ok, here it is:

```
$ go env
GOARCH="amd64"
GOBIN="/bin"
GOCACHE="/Users/hernan/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hernan/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/3r/5w6dq6zx6kg0fyfnqdl57h4c0000gn/T/go-build548267132=/tmp/go-build -gno-record-gcc-switches -fno-common"


$ go version
go version go1.11.1 darwin/amd64
```


Please let me know if you need to check something else.

**Comment by gcla** [comment] 2019-04-29 02:20
Thanks @hernanmd - I think the problem is that GOBIN is set to /bin. I'm not sure how it came to be that way, but could you try

$ unset GOBIN

in the shell before trying to install gowid? Or failing that,

$ export GOBIN="/Users/hernan/go/bin"

(and mkdir that directory if it's not there)

**Comment by gcla** [comment] 2019-05-21 23:17
I'll close this for now, but please re-open if it's still an issue.

**Closed by gcla** 2019-05-21 23:17 UTC
